<?php

namespace DoctrineORMModule\Proxy\__CG__\Sonar\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Issue extends \Sonar\Entity\Issue implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', '' . "\0" . 'Sonar\\Entity\\Issue' . "\0" . 'project', 'rule', 'severity', 'manualSeverity', 'line', 'status', 'resolution', 'message', 'assignee', 'effort_to_fix', 'technicalDebt', 'td', 'component_uuid', 'project_uuid', 'component_id');
        }

        return array('__isInitialized__', 'id', '' . "\0" . 'Sonar\\Entity\\Issue' . "\0" . 'project', 'rule', 'severity', 'manualSeverity', 'line', 'status', 'resolution', 'message', 'assignee', 'effort_to_fix', 'technicalDebt', 'td', 'component_uuid', 'project_uuid', 'component_id');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Issue $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getProject()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProject', array());

        return parent::getProject();
    }

    /**
     * {@inheritDoc}
     */
    public function setProject(\Sonar\Entity\Project $project)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setProject', array($project));

        return parent::setProject($project);
    }

    /**
     * {@inheritDoc}
     */
    public function getRule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRule', array());

        return parent::getRule();
    }

    /**
     * {@inheritDoc}
     */
    public function setRule(\Sonar\Entity\Rule $rule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRule', array($rule));

        return parent::setRule($rule);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeverity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeverity', array());

        return parent::getSeverity();
    }

    /**
     * {@inheritDoc}
     */
    public function setSeverity($severity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSeverity', array($severity));

        return parent::setSeverity($severity);
    }

    /**
     * {@inheritDoc}
     */
    public function getSeverityTag()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSeverityTag', array());

        return parent::getSeverityTag();
    }

    /**
     * {@inheritDoc}
     */
    public function getManualSeverity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManualSeverity', array());

        return parent::getManualSeverity();
    }

    /**
     * {@inheritDoc}
     */
    public function setManualSeverity($manualSeverity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setManualSeverity', array($manualSeverity));

        return parent::setManualSeverity($manualSeverity);
    }

    /**
     * {@inheritDoc}
     */
    public function getResolution()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getResolution', array());

        return parent::getResolution();
    }

    /**
     * {@inheritDoc}
     */
    public function setResolution($resolution)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setResolution', array($resolution));

        return parent::setResolution($resolution);
    }

    /**
     * {@inheritDoc}
     */
    public function getLine()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLine', array());

        return parent::getLine();
    }

    /**
     * {@inheritDoc}
     */
    public function setLine($line)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLine', array($line));

        return parent::setLine($line);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', array());

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', array($status));

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMessage', array());

        return parent::getMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMessage($message)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMessage', array($message));

        return parent::setMessage($message);
    }

    /**
     * {@inheritDoc}
     */
    public function getAssignee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAssignee', array());

        return parent::getAssignee();
    }

    /**
     * {@inheritDoc}
     */
    public function setAssignee($assignee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAssignee', array($assignee));

        return parent::setAssignee($assignee);
    }

    /**
     * {@inheritDoc}
     */
    public function getTechnicalDebt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTechnicalDebt', array());

        return parent::getTechnicalDebt();
    }

    /**
     * {@inheritDoc}
     */
    public function setTechinicalDebt($technicalDebt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTechinicalDebt', array($technicalDebt));

        return parent::setTechinicalDebt($technicalDebt);
    }

    /**
     * {@inheritDoc}
     */
    public function getTD()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTD', array());

        return parent::getTD();
    }

    /**
     * {@inheritDoc}
     */
    public function setTD($td)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTD', array($td));

        return parent::setTD($td);
    }

    /**
     * {@inheritDoc}
     */
    public function getComponentUUID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComponentUUID', array());

        return parent::getComponentUUID();
    }

}
