<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#assignTo<?=$issue->getId()?>Modal">
Assign To
</button>
<?php if ($issue->getAssignee()):?>
[<?=$issue->getAssignee()?>]
<?php endif;?>

<!-- Assign To Modal -->
<div class="modal fade" id="assignTo<?=$issue->getId()?>Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Assign To</h4>
      </div>
      <div class="modal-body">

        <select id="assignTo<?=$issue->getId()?>">
        	<option value="0">Select...</option>
      	<?php foreach ($users as $user):?>
      		<option value="<?php echo $user->getLogin();?>"><?php echo $user->getName()?></option>
      	<?php endforeach;?>        
        </select>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="<?=$issue->getId()?>" name="btnAssignTo<?=$issue->getId()?>">Save</button>
      </div>
    </div>
  </div>
</div>

