<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#comment<?=$issue->getId()?>Modal">
Comment
</button>

<!-- Comment Modal -->
<div class="modal fade" id="comment<?=$issue->getId()?>Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Comment</h4>
      </div>
      <div class="modal-body">
        <textarea rows="10" cols="90" id="comment<?=$issue->getId()?>"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="<?=$issue->getId()?>" name="btnComment<?=$issue->getId()?>">Save</button>
      </div>
    </div>
  </div>
</div>