<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#moreInfo<?=$issue->getId()?>Modal">
More Info
</button>

<!-- More Information Modal -->
<div class="modal fade bs-example-modal-lg" id="moreInfo<?=$issue->getId()?>Modal" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel"><?=$issue->getRule()->getName();?></h4>
      </div>
      <div class="modal-body">
       	<?=$issue->getRule()->getDescription();?>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
