<button type="button" class="btn btn-primary btn-xs" data-toggle="modal" data-target="#plan<?=$issue->getId()?>Modal">
Plan Payment
</button>

<!-- Plan Payment Modal -->
<div class="modal fade" id="plan<?=$issue->getId()?>Modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Plan Payment</h4>
      </div>
      <div class="modal-body">
        <textarea rows="10" cols="90" id="plan<?=$issue->getId()?>"></textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary" id="<?=$issue->getId()?>" name="btnPlan<?=$issue->getId()?>">Save</button>
      </div>
    </div>
  </div>
</div>